workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Set up Flutter
        script: |
          flutter --version
          flutter pub get
      - name: Pod install
        script: |
          cd ios
          pod install
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/**/outputs/bundle/**/*.aab
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - tu_email@ejemplo.com
